# -*- coding: utf-8 -*-
"""mikołajOnoszko1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ox2-PvBdfheOz0MJKjTVYxlj9wTqw5jL
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Tytuł aplikacji w Streamlit
st.title("🎅 Świąteczna Kartka w Pythonie")
st.write("Oto Twój wygenerowany obrazek:")

def prosty_niezawodny_mikolaj():
    # 1. Ustawiamy pustą kartkę
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.axis('off') # Wyłączamy osie
    ax.set_aspect('equal') # Żeby koła nie były jajowate

    # --- CHOINKA (Lewa strona) ---
    # Pień (brązowy prostokąt)
    pien = patches.Rectangle((20, 10), 10, 15, color='brown')
    ax.add_patch(pien)

    # Igły (3 zielone trójkąty)
    t1 = patches.Polygon([[5, 25], [45, 25], [25, 50]], color='green')
    t2 = patches.Polygon([[10, 40], [40, 40], [25, 60]], color='green')
    t3 = patches.Polygon([[15, 50], [35, 50], [25, 70]], color='green')
    ax.add_patch(t1)
    ax.add_patch(t2)
    ax.add_patch(t3)

    # Gwiazda (żółte kółko dla uproszczenia)
    gwiazda = patches.Circle((25, 70), 3, color='gold')
    ax.add_patch(gwiazda)

    # --- PREZENTY (Dół) ---
    # Niebieski prostokąt
    p1 = patches.Rectangle((35, 5), 10, 10, color='blue')
    ax.add_patch(p1)
    # Żółty prostokąt
    p2 = patches.Rectangle((50, 5), 10, 8, color='orange')
    ax.add_patch(p2)

    # --- MIKOŁAJ (Prawa strona) ---

    # 1. Nogi (Czarne prostokąty)
    noga_l = patches.Rectangle((70, 5), 5, 15, color='black')
    noga_p = patches.Rectangle((85, 5), 5, 15, color='black')
    ax.add_patch(noga_l)
    ax.add_patch(noga_p)

    # 2. Brzuch (Czerwone koło)
    brzuch = patches.Circle((80, 40), 18, color='red')
    ax.add_patch(brzuch)

    # 3. Pas (Czarny prostokąt)
    pas = patches.Rectangle((62, 38), 36, 4, color='black')
    ax.add_patch(pas)

    # 4. Ręce (Czerwone prostokąty pod kątem)
    reka_l = patches.Rectangle((60, 35), 5, 15, angle=45, color='red')
    reka_p = patches.Rectangle((95, 40), 5, 15, angle=-45, color='red')
    ax.add_patch(reka_l)
    ax.add_patch(reka_p)

    # Dłonie (czarne kółka)
    dlony_l = patches.Circle((55, 30), 3, color='black')
    dlony_p = patches.Circle((105, 30), 3, color='black')
    ax.add_patch(dlony_l)
    ax.add_patch(dlony_p)

    # 5. BRODA (Wielkie brązowe koło - wg Twojego kodu)
    broda = patches.Circle((80, 58), 12, color='brown')
    ax.add_patch(broda)

    # 6. Twarz (Różowe koło)
    twarz = patches.Circle((80, 65), 8, color='#ffccaa') # Kolor skóry
    ax.add_patch(twarz)

    # 7. Oczy i Nos
    oko_l = patches.Circle((77, 67), 1, color='black')
    oko_p = patches.Circle((83, 67), 1, color='black')
    nos = patches.Circle((80, 64), 2, color='red')
    ax.add_patch(oko_l)
    ax.add_patch(oko_p)
    ax.add_patch(nos)

    # 8. Czapka
    czapka = patches.Polygon([[70, 70], [90, 70], [80, 85]], color='red')
    ax.add_patch(czapka)
    rondo = patches.Rectangle((68, 68), 24, 4, color='white')
    ax.add_patch(rondo)

    # Pompon (zielony - wg Twojego kodu)
    pompon = patches.Circle((80, 85), 3, color='green')
    ax.add_patch(pompon)

    # Zaktualizowany tytuł wykresu
    plt.title("Prosty Mikołaj w Streamlit", color='red')

    # WAŻNE: Zamiast plt.show(), zwracamy obiekt figury
    return fig

# Wywołanie funkcji i wyświetlenie w Streamlit
figura = prosty_niezawodny_mikolaj()
st.pyplot(figura)